c_compiler:
- gcc
c_compiler_version:
- '12'
cdt_name:
- cos7
cdt_arch:
- armv7l
channel_sources:
- conda-forge
channel_targets:
- conda-forge lapack_rc
docker_image:
- quay.io/condaforge/linux-anvil-cos7-x86_64
fortran_compiler:
- gfortran
fortran_compiler_version:
- '12'
target_platform:
- linux-armv7l
zip_keys:
- - c_compiler_version
  - fortran_compiler_version
