c_compiler:
- gcc
c_compiler_version:
- '12'
cdt_name:
- cos7
cdt_arch:
- armv7l
channel_sources:
- conda-forge,defaults
channel_targets:
- conda-forge main
docker_image:
- quay.io/condaforge/linux-anvil-comp7
fortran_compiler:
- gfortran
fortran_compiler_version:
- '12'
target_platform:
- linux-armv7l
zip_keys:
- - c_compiler_version
  - fortran_compiler_version
- - cdt_name
  - docker_image
